apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf1
  namespace: 5gc-smf
spec:
  selector:
    matchLabels:
      app: smf1
  replicas: 1
  template:
    metadata:
      labels:
        app: smf1
      annotations:
        k8s.v1.cni.cncf.io/networks: eno4-n4-smf
    spec:
      hostname: smf1
      containers:
      - name: smf1-container
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "/root/run/start.sh; while true; do sleep 100000; done;" ]
        image: private.el:5000/smf:0.0.6
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
          - name: smf-run
            mountPath: /root/run/
          - name: smf-log
            mountPath: /SMF/log
          - name: 5gc-license
            mountPath: /lib/5gc-license
      volumes:
      - name: smf-run
        configMap:
          name: smf-run
          defaultMode: 0770
      - name: smf-log
        hostPath:
          path: /root/asu/log/SMF
      - name: 5gc-license
        hostPath:
          path: /lib/5gc-license

