apiVersion: v1
kind: Service
metadata:
  name: access-core-smf
  namespace: 5gc-smf
  labels:
    app: smf1
spec:
  selector:
    app: smf1
  ports:
    - name: http2
      port: 80
      targetPort: 80
